# Header
menu:
  首页: /
  归档: /archives
  关于: /about
rss: /atom.xml

# Content
excerpt_link: 阅读更多
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- archive
- recent_posts
- links

# Links
links:
  碧海听涛: http://168love.cn

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: feijl-cn

# Baidu share
baidushare: true